version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "crypto-alarm"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1fdkzafqzj52l"
s3_prefix = "crypto-alarm"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
