AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: A sample SAM template for deploying Lambda functions.

Resources:
  # Details about the cryptoAlarm Lambda function
  cryptoAlarm:
    Type: AWS::Serverless::Function
    Properties:
      Handler: cryptoAlarm.handler
      Runtime: nodejs12.x
      # Instructs your cryptoAlarm is published to an alias named "live".
      AutoPublishAlias: live
      # Grants this function permission to call lambda:InvokeFunctionEvents:
      Events:
        cryptoAlarm:
          Type: Schedule
          Properties:
            Schedule: rate(20 minute)
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action:
                - "lambda:InvokeFunction"
              Resource: "*"
